accounts/urls.py
from django.urls import path , include
from . import views

app_name='job'
urlpatterns = [
    path('signup',views.signup ,name='signup'),
    path('profile',views.profile , name='profile'),
    path('profile/edit',views.profile_edit , name='profile_edit'),
  

]

contact/urls.py
from django.urls import path , include
from . import views

app_name='contact'
urlpatterns = [
    path('',views.send_message ,name='contact'),
  

]

job/urls.py
from django.urls import path , include
from . import views

app_name='job'
urlpatterns = [
    path('',views.job_list ,name='job_list'),
    path('add',views.add_job ,name='add_job'),
    path('<str:slug>',views.job_detail ,name='job_datil'),


]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls' , namespace='accounts')),
    path('admin/', admin.site.urls),
    path('jobs/', include('job.urls', namespace='jobs')),
    path('contact/', include('contact.urls', namespace='contact')),
]
urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver



# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    city =models.ForeignKey('City', related_name='user_city', on_delete=models.CASCADE , blank=True, null=True) 
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    image = models.ImageField( upload_to='profile/')

    def __str__(self):
        return str(self.user)
    

#انشاء البروفايل الخاص باليوزر
@receiver(post_save , sender=User)
def create_user_profile(sender,instance , created , **kwargs):
    if created:
        Profile.objects.create(user=instance)



class City(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

blog/models.py
from django.db import models

# Create your models here.

contact/models.py
from django.db import models

# Create your models here.

class Info(models.Model):
    place = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField(max_length=250)


    class Meta:
        verbose_name = ("Info")
        verbose_name_plural = ("Infos")

    def __str__(self):
        return self.email

home/models.py
from django.db import models

# Create your models here.

job/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.

JOB_TYPE = (
    ('Full Time','Full Time'),
    ('Part Time','Part Time'),
)

def image_upload(instance , filename):
    imagename , extension = filename.split(".")
    return "jobs/%s.%s"%(instance.id,extension)

class job(models.Model):
    owner = models.ForeignKey(User,related_name='job_owner' , on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    # location
    job_type = models.CharField(max_length=15 , choices=JOB_TYPE)
    descraption = models.TextField(max_length=1000)
    published_at = models.DateTimeField(auto_now=True)
    vacancy = models.IntegerField(default=1)
    salary = models.IntegerField(default=0)
    experience = models.IntegerField(default=1)
    category = models.ForeignKey( 'Category' ,on_delete=models.CASCADE,null=True)
    image = models.ImageField(upload_to=image_upload)
    
    slug = models.SlugField(null=True,blank=True)



    def save(self,*args, **kwargs):
        self.slug =slugify(self.title)
        super(job,self).save(*args,**kwargs)

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=25)

    
    def __str__(self):
        return self.name

class Apply(models.Model):
    job = models.ForeignKey( 'job' ,related_name='apply_job' ,on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    webiste = models.URLField()
    cv = models.FileField(upload_to='apply')
    cover_letter = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.name

    

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User 
from .models import Profile


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
    
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['city','phone_number','image']

accounts/views.py
from django.shortcuts import redirect, render
from .forms import SignupForm , ProfileForm , UserForm
from django.contrib.auth import authenticate, login
from .models import Profile
from django.urls import reverse

# Create your views here.

def signup(request):
    if request.method=="POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request,user)
            return redirect('/accounts/profile/')
    else:
        form = SignupForm()
    return render(request , 'registration\signup.html' , {'form':form})


def profile(request):
    profile = Profile.objects.get(user=request.user)
    return render(request,'accounts/profile.html',{'profile': profile})


def profile_edit(request):
    profile = Profile.objects.get(user=request.user)
    if request.method=='POST':
        userform = UserForm(request.POST, instance=request.user)
        profileform = ProfileForm(request.POST,request.FILES , instance=profile)
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            myProfileform = profileform.save(commit=False)
            myProfileform.user = request.user
            myProfileform.save()
            return redirect(reverse('accounts:profile'))

    else:
        userform = UserForm(instance=request.user)
        profileform = ProfileForm(instance=profile)

    return render(request,'accounts\profile_edit.html',{'userform':userform ,'profileform':profileform })
    

blog/views.py
from django.shortcuts import render

# Create your views here.

contact/views.py
from django.shortcuts import render

# Create your views here.

def send_message(request):
    
    return render(request, 'contact/contact.html' ,{})

home/views.py
from django.shortcuts import render

# Create your views here.

job/views.py
from django.shortcuts import redirect, render
from .models import job
from django.core.paginator import Paginator
from .form import ApplyForm , JobForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .filters import jobFilter

# Create your views here.
def job_list(request):
    job_list = job.objects.all()
    # filter
    myfilter = jobFilter(request.GET,queryset=job_list)
    job_list = myfilter.qs


    paginator = Paginator(job_list, 5) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request,'job/job_list.html',{'jobs':page_obj , 'myfilter':myfilter})

def job_detail(request,slug):
    job_detail = job.objects.get(slug=slug)

    if request.method=='POST':
        form = ApplyForm(request.POST , request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.job = job_detail
            myform.save()

    else:
        form = ApplyForm()

    context = {'job':job_detail , 'form1':form}
    return render(request , 'job/job_detils.html' , context)

@login_required
def add_job(request):
    if request.method == 'POST':
        form = JobForm(request.POST , request.FILES)
        if  form.is_valid():
            myform = form.save(commit=False)
            myform.owner = request.user
            myform.save()
            return redirect(reverse('jobs:job_list'))
            
    else:
        form = JobForm()
    
    return render(request,'job/add_job.html',{'form2':form})

contact/templates/contact/contact.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
  

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>contact</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->
  <!-- ================ contact section start ================= -->
  <section class="contact-section section_padding">
    <div class="container">
     


      <div class="row">
        <div class="col-12">
          <h2 class="contact-title">Get in Touch</h2>
        </div>
        <div class="col-lg-8">
          <form class="form-contact contact_form" action="contact_process.php" method="post" id="contactForm" novalidate="novalidate">
            <div class="row">
              <div class="col-12">
                <div class="form-group">
                  
                    <textarea class="form-control w-100" name="message" id="message" cols="30" rows="9" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Message'" placeholder = 'Enter Message'></textarea>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <input class="form-control" name="name" id="name" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your name'" placeholder = 'Enter your name'>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <input class="form-control" name="email" id="email" type="email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" placeholder = 'Enter email address'>
                </div>
              </div>
              <div class="col-12">
                <div class="form-group">
                  <input class="form-control" name="subject" id="subject" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Subject'" placeholder = 'Enter Subject'>
                </div>
              </div>
            </div>
            <div class="form-group mt-3">
              <button type="submit" class="button button-contactForm btn_4 boxed-btn">Send Message</button>
            </div>
          </form>
        </div>
        <div class="col-lg-4">
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-home"></i></span>
            <div class="media-body">
              <h3>Buttonwood, California.</h3>
              <p>Rosemead, CA 91770</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-tablet"></i></span>
            <div class="media-body">
              <h3>00 (440) 9865 562</h3>
              <p>Mon to Fri 9am to 6pm</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-email"></i></span>
            <div class="media-body">
              <h3>support@colorlib.com</h3>
              <p>Send us your query anytime!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- ================ contact section end ================= -->
{% endblock body %}

job/templates/job/add_job.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block body%}



<div class="bradcam_text " >
    <br>
    <br>
    <br>
    <br>
    <br>
</div>
<div dir="rtl">

<div class="bradcam_area bradcam_bg_1 ">
        <div class="container "  style="margin-right: 30rem">
        <div class="row" >
            <div class="col-lg-3 col-md-4 " >
            <div class=" bradcam_text ">
                <h1>اضافة وظيفة</h1>
                </div>
                <br>
            </div>
        </div>
            
        
    </div>
</div>


    <!-- bradcam_area  --> 




  
  <div dir="rtl">
    <div class="container">
        <div class="signup">
    
        <div class="col-lg-9 mx-auto" >
            <form  method="POST" enctype="multipart/form-data">
           <h4>اضف وظيفة جدبدة</h4>

                {% csrf_token %}
                {% bootstrap_form form2 %}
                {% buttons %}
                    <button type="submit" class="boxed-btn3 w-100">اضافة </button>
                {% endbuttons %}

            </form>

        </div>
        </div>
    </div>
    </div>


{% endblock body%}

job/templates/job/job_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block body%}




<div class="bradcam_text " >
    <br>
    <br>
    <br>
    <br>
    <br>
</div>
<div dir="rtl">

<!--/ bradcam_area  -->

    
<!-- Search -->
<div class="catagory_area ">
    <div class="container " style="margin-top: 10rem">
        <div class=" single_text">
            <h1>اكثر من {{jobs.count}}+وضائف  متاحة</h1>
            <br>
        </div>
        
        <!-- endsearch -->
    </div>
    <!-- bradcam_area  -->  

       
<!--================Blog Area =================-->
<section class="blog_area section-padding">
<div class="container" >
    <div class="row">


   
        {% for job in jobs %}
 
        <div class="col-lg-8 mb-5 mb-lg-0">
            <div class="blog_left_sidebar">
                <article class="blog_item" style="background-color: rgba(142, 197, 248, 0.63);">
                    <div class="blog_details">
                        <img class="img-circle" src="{{job.image.url}}" alt="" style="width:50px;height:60px;">
                        <a href="#" class="blog_item_date">
                            <h5>date : {{job.published_at|date:"d M o"}}</h5>
                            
                    
                      
                     
                        <a class="d-inline-block" href="{% url 'jobs:job_datil' job.slug %}">
                            <h2>{{job}}</h2>
                        </a>
                        <p> {{job.descraption}} </p>
                        <ul class="blog-info-link">
                            <li><a href="#"><i class="fa fa-user"></i> Travel, Lifestyle</a></li>
                            <li><a href="#"><i class="fa fa-comments"></i> 03 Comments</a></li>
                        </ul>
                    </div>
                </article>

                
            </div>
        </div>
        
        {% endfor %}






        <!-- @@@@@@@@@@@@@@@@@@@@@@@@ -->
        








        

        <div class="col-lg-4">
            <div class="blog_right_sidebar">
                <aside class="single_sidebar_widget search_widget">
                    <form method="GET">
                        {% bootstrap_form myfilter.form %}
                   
                            <input type="submit" value="إبحث" class="boxed-btn3 w-100">
                    </form>
                </aside>

                <aside class="single_sidebar_widget popular_post_widget">
                    <h3 class="widget_title">احدث الوضائف</h3>


                        <div class="media post_item">
                                <img src="img/blog/single_blog_1.png" alt="" style="width: 30spx; height: 30px;">
                            <div class="media-body">
                                <a href="single-blog.html">
                                    <h3>تجميل وزراعه الاسنان</h3>
                                </a>
                                <p>تم النتشر في : <span style="color: #00D363;">3/6/2020</p>
                            </div>
                        </div>
                    

                </aside>
            </div>
        </div>
    </div>
</div>
</section>
<!--================Blog Area =================-->
</div>
     








<!-- @@@@@@@@@@@@@@@@@@@@ -->
{% if jobs.has_other_pages %}

    <div class="col-lg-8 mb-5 mb-lg-0"> 
        <nav class="blog-pagination justify-content-center d-flex">
            <ul class="pagination">
                <li class="page-item">
                    {% if jobs.has_previous %}
                    <a href="?page={{jobs.previous_page_number}}" class="page-link" aria-label="Previous">
                        <i class="ti-angle-right"></i>
                    </a>
                    {% endif %}
                </li>
                
                        {% for i in jobs.paginator.page_range %}        
                            <li class="page-item active">
                                <a href="?page={{i}}" class="page-link">{{i}}</a>
                            </li>
                        {%endfor%}     
                <li class="page-item">
                    {% if jobs.has_next %}
                    <a href="?page={{jobs.next_page_number}}" class="page-link" aria-label="Next">
                        <i class="ti-angle-right"></i>
                    </a>
                    {% endif %}

                </li>
                
            </ul>
        </nav>
        
    </div>
{% endif %}

{% endblock body%}

templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block body%}



<div class="bradcam_text " >
    <br>
    <br>
    <br>
    <br>
    <br>
</div>
<div dir="rtl">
    <!-- bradcam_area  -->



  <!--/ bradcam_area  -->



  
<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
               
                
                




                
    
            <div class="col-lg-8 mx-auto">
                <div class="job_sumary">
                    <div class="summery_header">
                        <h3>الصفحه الشخصية </h3>
                    </div>
                    <div class="job_content">
                        <ul>
                            <li>Name: <span>{{profile}}</span></li>
                            <li>Email: <span>{{profile.user.email}}</span></li>
                            <li>Phone: <span>{{profile.phone_number}}</span></li>
                            <li>Address: <span>{{profile.city}}</span></li>

                        </ul>
                        
                    </div>
                    <div class="p-5">
                        <a class="boxed-btn3 w-100" href="{% url 'accounts:profile_edit' %}"> Edit Profile</a>
                    </div>
                </div>
             
              
            </div>
        </div>
    </div>
    </div>
    </div>


{% endblock body%}

templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block body%}



<div class="bradcam_text " >
    <br>
    <br>
    <br>
    <br>
    <br>
</div>
<div dir="rtl">

<div class="bradcam_area bradcam_bg_1 ">
        <div class="container "  style="margin-right: 30rem">
       
            
        
    </div>
</div>


    <!-- bradcam_area  --> 




  
  <div dir="rtl">
    <div class="container">
        <div class="signup">
    
        <div class="col-lg-9 mx-auto" >
            <form  method="POST" enctype="multipart/form-data">
           <h4>تعديل البروفايل</h4>

                {% csrf_token %}
                {% bootstrap_form userform %}
                {% bootstrap_form profileform %}
                {% buttons %}
                    <button type="submit" class="boxed-btn3 w-100">حفظ </button>
                {% endbuttons %}

            </form>

        </div>
        </div>
    </div>
    </div>


{% endblock body%}

templates/base.html
{% load static%}
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">



    <title>Vezeta</title>

    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.png'%}">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css'%}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css'%}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css'%}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css'%}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>

<!-- header-start -->
<header>
<div class="header-area ">
    <div id="sticky-header" class="main-header-area">
        <div class="container-fluid " style="background-color: rgba(0, 29, 56, 0.8);" >
            <div class="header_bottom_border">
                <div class="row align-items-center">
                    <div class="col-xl-3 col-lg-2">
                        <div class="logo">
                            <a href="index.html">
                                <img src="{% static 'img/logo2.png'%}" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-5 col-lg-7">
                        <div class="main-menu  d-none d-lg-block">
                            <nav>
                                <ul id="navigation">
                                    <li><a href="">الصفحة الرئيسية</a></li>|
                                    <li><a href="{% url 'jobs:job_list' %}">الوظائف المتاحة</a></li>|
                                    <li><a href="{% url 'contact:contact'%}">اتصل بنا</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                        <div class="Appointment">
                            
                            <div class="phone_num d-none d-xl-block">
                                <a class="boxed-btn3" href="{% url 'jobs:add_job' %}">اضف وظيفة </a>
                            </div>
                            
                            {% if request.user.is_authenticated %}
                                <div class="phone_num d-none d-xl-block">
                                    <a class="boxed-btn3" href="{% url 'accounts:profile'%}"> الصفحة الشخصية</a>
                                </div>

                            {% else %}
                                <div class="phone_num d-none d-xl-block">
                                    <a class="boxed-btn3" href="{% url 'login'%}">سجل الدخول</a>
                                </div>
                                <div class="d-none d-lg-block">
                                    <a class="boxed-btn3" style="background-color: crimson;" href="">التسجيل</a>
                                </div>
                            {% endif %}
                                
                           
                            
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="mobile_menu d-block d-lg-none"></div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
</header>
<!-- header-end -->


<div dir="rtl">
   


 
{% block body%}


{% endblock body%}






<!-- footer start -->
<footer class="footer">
<div class="footer_top">
<div class="container">
    <div class="row">
        <div class="col-xl-3 col-md-6 col-lg-3">
            <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                <div class="footer_logo">
                    <a href="#">
                        <img src="img/logo2.png" alt="">
                    </a>
                </div>
                <p>
                    ma7mod.raouf@gmail.com <br>
                    +01005162422 <br>
                    Mansora, Egypt
                </p>
                <div class="socail_links">
                    <ul>
                        <li>
                            <a href="https://www.facebook.com/m7modsabra">
                                <i class="ti-facebook"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.youtube.com/channel/UC7FFcZc90vE5FfR_dgA_dVg?view_as=subscriber">
                                <i class="fa fa-youtube"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://twitter.com/Mahmod_Raouf">
                                <i class="fa fa-twitter"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://twitter.com/Mahmod_Raouf">
                                <i class="fa fa-instagram"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xl-2 col-md-6 col-lg-2">
            <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                <h3 class="footer_title">
                    ماذا عنا
                </h3>
                <ul>
                    <li><a href="https://code4learn.teachable.com/p/online-courses">من نحن </a></li>
                    <li><a href="https://code4learn.teachable.com/p/online-courses"> أسعارنا</a></li>
                    <li><a href="https://www.facebook.com/m7modsabra">إستفسار</a></li>
                </ul>

            </div>
        </div>
        <div class="col-xl-3 col-md-6 col-lg-3">
            <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                <h3 class="footer_title">
                    الخدمات
                </h3>
                <ul>
                    <li><a href="https://code4learn.teachable.com/p/soundcloud">اعمالنا</a></li>
                    <li><a href="https://twitter.com/code4learn/status/1236082742582001670?s=21">شركائنا</a></li>
                    <li><a href="https://code4learn.teachable.com/p/online-courses">الخصومات والمشاريع</a></li>
                    <li><a href="https://www.facebook.com/m7modsabra">للإعلان</a></li>
                </ul>
            </div>
        </div>
        <div class="col-xl-4 col-md-6 col-lg-4">
            <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                <h3 class="footer_title">
                    Subscribe
                </h3>
                <form action="#" class="newsletter_form">
                    <input type="text" placeholder="Enter your mail">
                    <button type="submit">Subscribe</button>
                </form>
                <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems
                    luckily.</p>
            </div>
        </div>
    </div>
</div>
</div>
<div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
<div class="container">
    <div class="footer_border"></div>
    <div class="row">
        <div class="col-xl-12">
            <p class="copy_right text-center">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
        </div>
    </div>
</div>
</div>
</footer>
<!--/ footer end  -->

<!-- link that opens popup -->
<!-- JS here -->
<script src="js/vendor/modernizr-3.5.0.min.js"></script>
<script src="js/vendor/jquery-1.12.4.min.js"></script>
<script src="js/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/owl.carousel.min.js"></script>
<script src="js/isotope.pkgd.min.js"></script>
<script src="js/ajax-form.js"></script>
<script src="js/waypoints.min.js"></script>
<script src="js/jquery.counterup.min.js"></script>
<script src="js/imagesloaded.pkgd.min.js"></script>
<script src="js/scrollIt.js"></script>
<script src="js/jquery.scrollUp.min.js"></script>
<script src="js/wow.min.js"></script>
<script src="js/nice-select.min.js"></script>
<script src="js/jquery.slicknav.min.js"></script>
<script src="js/jquery.magnific-popup.min.js"></script>
<script src="js/plugins.js"></script>
<script src="js/gijgo.min.js"></script>



<!--contact js-->
<script src="js/contact.js"></script>
<script src="js/jquery.ajaxchimp.min.js"></script>
<script src="js/jquery.form.js"></script>
<script src="js/jquery.validate.min.js"></script>
<script src="js/mail-script.js"></script>


<script src="js/main.js"></script>
</body>

</html>

templates/base_generic.html
{% extends 'base.html' %}
{% load static%}
{% load bootstrap4 %}
{% block body %}


<!-- @@@@@@@@@@@@@@@@@2 -->

<div class="bradcam_text " >
    <br>
    <br>
    <br>
    <br>
    <br>
</div>

    
<!-- 
<div class="bradcam_area bradcam_bg_1 ">
        <div class="container "  style="margin-right: 30rem">
        <div class="row" >
            <div class="col-lg-3 col-md-4 " >
            <div class=" bradcam_text ">
                <h1>تسجيل دخول</h1>
                </div>
                <br>
            </div>
        </div>
            
        
    </div>
</div> -->


    <!-- bradcam_area  --> 




  
  <div dir="rtl" lang="en">
    <div class="container">
        <div class="signup">
    
        <div class="col-lg-9 mx-auto" >
            {% block content %}
  
            {% endblock content %}
            

        </div>
        </div>
    </div>
    </div>

  
  
{% endblock body %}